---
- hosts: qaserver
  become: yes
  ignore_error: yes
    tasks:
      - name: Install packages
        packages:
          name: "{{ item }}"
          state: present
          with_items:
            - unzip
            - wget
            - httpd


